//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdd
    {
        public int Code { get; set; }
        public int Class { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> QuantityS { get; set; }
    }
}
